title: S. Tolga Er
description: PhD Candidate in Economics

theme: jekyll-theme-minimal

logo: https://via.placeholder.com/140x140.png?text=Photo

show_downloads: false

github:
  is_project_page: false
